server:
    port: ${PORT:8000}

spring:
    application:
        name: mockboard
    main:
        banner-mode: off
    profiles:
        active: ${ACTIVE_ENV:dev}
    threads:
        virtual:
            enabled: ${VI_THREADS:true}
    mongodb:
        uri: ${MONGO_URI:mongodb://localhost:27017/mockboard_db}
    data:
        mongodb:
            auto-index-creation: true

mockboard:
    security:
        owner-token-header-key: ${OWNER_TOKEN_HEADER:'X-Owner-Token'}
    cache:
        max-entries: ${CACHE_MAX_ENTRIES:10000}
        exp-after-access-minutes: ${CACHE_EXP_AFTER_ACCESS_MIN:30}
        rate-limiter:
            board-creation-exp-after-access-minutes: ${BOARD_CREATION_CACHE_EXP_AFTER_MIN:60}
            mock-execution-exp-after-access-minutes: ${MOCK_EXECUTION_CACHE_EXP_AFTER_MIN:1}