spring:
    datasource:
        url: jdbc:h2:mem:mockboard_dev;DB_CLOSE_DELAY=-1;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
        username: sa
        password:
        driver-class-name: org.h2.Driver