spring:
    application:
        name: mockboard
    main:
        banner-mode: off
    output:
        ansi:
            enabled: always
    profiles:
        active: dev
    mongodb:
        uri: mongodb://admin:admin123@localhost:27017/mockboard?authSource=admin
    data:
      mongodb:
          auto-index-creation: true

server:
    port: 8080

logging:
    level:
        root: INFO
        dev.mockboard: DEBUG
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"